NameError: name 'a' is not defined

In [ ]:

a=10
b=20

a+b

30

In [4]:


! pip install torch

   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 2.4/203.0 MB 12.2 MB/s eta 0:00:17
    --------------------------------------- 4.2/203.0 MB 11.0 MB/s eta 0:00:19
   - -------------------------------------- 6.3/203.0 MB 10.4 MB/s eta 0:00:19
   - -------------------------------------- 8.7/203.0 MB 10.5 MB/s eta 0:00:19
   -- ------------------------------------- 11.0/203.0 MB 10.6 MB/s eta 0:00:19
   -- ------------------------------------- 12.6/203.0 MB 10.5 MB/s eta 0:00:19
   -- ------------------------------------- 14.4/203.0 MB 10.0 MB/s eta 0:00:19
   --- ------------------------------------ 16.0/203.0 MB 9.7 MB/s eta 0:00:20
   --- ------------------------------------ 16.8/203.0 MB 9.7 MB/s eta 0:00:20
   --- ------------------------------------ 19.4/203.0 MB 9.4 MB/s eta 0:00:20
   ---- ----------------------------------- 22.5/203.0 MB 9.9 MB/s eta 0:00:19
   ---- ----------------------------------- 25.2/203.0 MB

In [5]:
import torch
t1 = torch.tensor([1, 2, 3])
t1

tensor([1, 2, 3])

In [7]:
t2 = torch.tensor([[1, 2, 3],[4,5,6]])
t2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
t1 =torch.tensor([[1, 2], [4, 5]])
#t2=torch.tersor([[1, 2,], [3, 4]], device="cuda:0")
t3=torch.tensor([[1,2], [3,4]], dtype=torch.float64)
print(t1)
print(t2)
print(t3)

tensor([[1, 2],
        [4, 5]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [10]:
tf = torch.FloatTensor([[1,2],[3,4]])
tl = torch.LongTensor([[1,2],[3,4]])
tb = torch.ByteTensor([[1,2],[3,4]])

print(tf)
print(tl)
print(tb)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [12]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [13]:
t=torch.from_numpy(x)
print(t)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [ ]:
x1 = t.numpy()
print(x1)
print(type(x1))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [15]:
print(tf.long())

tensor([[1, 2],
        [3, 4]])


In [16]:
print(tl.float())

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print(tf.byte())

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


텐서 크기 구하기

In [21]:
x=np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
x=np.arange(1,13).reshape(3,2,2)
x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
tx=torch.from_numpy(x)
tx

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [31]:
print('numpy 배열 크기', x.shape)
print('tensor 크기', tx.shape)
print(tx.size())
print(tx.shape[0])
print(tx.size(0))
print(tx.size(1))
print(tx.size(2))
print(tx.size(-1))
print('차원의 수', tx.dim())
print('차원의 수', len(tx.size()))

numpy 배열 크기 (3, 2, 2)
tensor 크기 torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3
2
2
2
차원의 수 3
차원의 수 3


In [ ]:
a = np.arange(1, 5).reshape(2, 2)
print(a)
b =np.arange(2, 10, 2)
print(b)
c = np.arange(2,10,2).reshape(2, 2)
print(c)

ta=torch.from_numpy(a)
tb=torch.from_numpy(b)
print(ta)
print(tb)

[[1 2]
 [3 4]]
[2 4 6 8]
[[2 4]
 [6 8]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([2, 4, 6, 8], dtype=torch.int32)


텐서의 연산

In [43]:
print(ta+ta)
print(ta - ta)
print(ta * ta)

tensor([[2, 4],
        [6, 8]], dtype=torch.int32)
tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
tensor([[ 1,  4],
        [ 9, 16]], dtype=torch.int32)


In [46]:
print(ta)
print(ta.mul_(ta))
print(ta)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[ 1,  4],
        [ 9, 16]], dtype=torch.int32)
tensor([[ 1,  4],
        [ 9, 16]], dtype=torch.int32)


In [48]:
x = np.arange(1, 10).reshape(3, 3)
tx = torch.from_numpy(x)
tx

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [50]:
print(x.mean())

5.0


In [55]:
x = np.arange(1, 5).reshape(2, 2)
t1 = torch.from_numpy(x)
y = 1
print ( t1)
print ( t1 + y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[2, 3],
        [4, 5]], dtype=torch.int32)


In [57]:
t2 = torch.tensor([1, 2])
print(t1)
print(t2)
print(t1 + t2)


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([1, 2])
tensor([[2, 4],
        [4, 6]])


In [58]:
t3 = np.arange(1, 7).reshape(2, 3)
print(t1, t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) [[1 2 3]
 [4 5 6]]


In [61]:
x = np.arange(1, 13).reshape(3, 2, 2)
x = torch.from_numpy(x) #텐서로 바뀜
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [65]:
#3행 4열로 바꿀 것임
print(x.view(3,4))
print(x.view(6,2))
print(x.view(3,-1,2)) #-1이 붙으면 나머지는 알아서 정하라는 뜻

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [ ]:
x1 = x.view(3, -1, 4)
print(x1)
x2 = x1.squeeze()
print(x2)
x3 = x2.unsqueeze(1) #인덱스 1인 위치에 크기가 1인 차원 추가
print(x3)


tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)


tensor 자르기 & 붙이기

In [71]:
print(x)
print(x.size())

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)
torch.Size([3, 2, 2])


In [74]:
print(x[0,:])

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [75]:
print([x[-1]])
print([x[-2]])
print([x[-2, :]])
print([x[-2, :, :]])

[tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)]
[tensor([[5, 6],
        [7, 8]], dtype=torch.int32)]
[tensor([[5, 6],
        [7, 8]], dtype=torch.int32)]
[tensor([[5, 6],
        [7, 8]], dtype=torch.int32)]


In [76]:
print(x[1:3 , :, :]) #맨 마지막 3차원은 빼고 가져옴

tensor([[[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)


In [85]:
x = np.arange(1, 101).reshape(10, 10)

#x = torch.FloatTensor(10, 4)  #값을 랜덤하게 뿌림

x = torch.from_numpy(x)
print(x) 

tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]], dtype=torch.int32)


In [86]:
#한번에 4개씩 자르기

splits = x.split(4, dim=1)
for s in splits:
    print(s.size())
    print(s)
    

torch.Size([10, 4])
tensor([[ 1,  2,  3,  4],
        [11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34],
        [41, 42, 43, 44],
        [51, 52, 53, 54],
        [61, 62, 63, 64],
        [71, 72, 73, 74],
        [81, 82, 83, 84],
        [91, 92, 93, 94]], dtype=torch.int32)
torch.Size([10, 4])
tensor([[ 5,  6,  7,  8],
        [15, 16, 17, 18],
        [25, 26, 27, 28],
        [35, 36, 37, 38],
        [45, 46, 47, 48],
        [55, 56, 57, 58],
        [65, 66, 67, 68],
        [75, 76, 77, 78],
        [85, 86, 87, 88],
        [95, 96, 97, 98]], dtype=torch.int32)
torch.Size([10, 2])
tensor([[  9,  10],
        [ 19,  20],
        [ 29,  30],
        [ 39,  40],
        [ 49,  50],
        [ 59,  60],
        [ 69,  70],
        [ 79,  80],
        [ 89,  90],
        [ 99, 100]], dtype=torch.int32)


10개니까 4개, 4개 나머지 2개로 자름

In [ ]:
chunks = x.chunk(3, dim=0) #블럭이 3개라는 뜻
for c in chunks:
    print(c)
    print(c.size)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], dtype=torch.int32)
<built-in method size of Tensor object at 0x000001E8A38719A0>
tensor([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]], dtype=torch.int32)
<built-in method size of Tensor object at 0x000001E8A3870C80>
tensor([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]], dtype=torch.int32)
<built-in method size of Tensor object at 0x000001E8AB6D5720>


In [94]:
x = np.arange(1, 19).reshape(2,3,3)
x =torch.from_numpy(x)
print(x)
indice = torch.LongTensor([2,0])
y = x.index_select(dim=-1, index=indice)

print(y)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=torch.int32)
tensor([[[ 3,  1],
         [ 6,  4],
         [ 9,  7]],

        [[12, 10],
         [15, 13],
         [18, 16]]], dtype=torch.int32)


In [100]:
a = np.arange(1, 7).reshape(2,3)
a = torch.from_numpy(a)
print(a)

b = np.arange(7, 13).reshape(2,3)
b = torch.from_numpy(b)
print(b)

c = torch.stack([a, b])
print(c)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)


In [101]:
d = torch.stack([a,b], dim = -1)
print(d)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]], dtype=torch.int32)


In [103]:
e = torch.cat([a, b])
print(e)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [113]:
a1 = a.view(2, 1, 3)
print(a1)
a2 = a1.expand(2, 3, 3)
print(a2)

print(torch.cat([a1]*3, dim=1))

tensor([[[1, 2, 3]],

        [[4, 5, 6]]], dtype=torch.int32)
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]], dtype=torch.int32)
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]], dtype=torch.int32)


In [114]:
x=torch.randperm(100)
print(x)

tensor([26, 53, 58, 10, 81, 84, 37, 13, 99, 75, 36, 33, 59, 23, 91, 93, 12, 39,
         9, 78, 64, 62, 34, 41, 22, 98, 55, 76, 86,  7, 20, 96, 67, 70, 71, 42,
        44,  8, 50, 30, 51,  6, 11, 56, 28,  5, 16, 48, 24, 18,  3, 52, 14, 88,
        83, 45, 89, 97, 54, 38, 90, 80, 27, 60, 66, 63,  2, 35, 47, 74, 21, 68,
        43, 95, 72, 73,  4, 29, 87, 92,  0, 65, 31, 17, 82, 79, 94, 25,  1, 85,
        49, 57, 69, 61, 19, 77, 32, 40, 15, 46])


In [116]:
x= torch.randperm(3**3).reshape(3,3,-1)
print(x)

tensor([[[12, 14, 18],
         [23,  5, 13],
         [19, 10, 24]],

        [[25,  7,  0],
         [17,  8, 16],
         [21,  2,  1]],

        [[15, 22, 11],
         [ 6, 20, 26],
         [ 3,  9,  4]]])
