In [3]:
import torch
import torch.nn.functional as F

In [5]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0) #1차원 순서대로 1/6 2/6 3/6
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [13]:
z=torch.rand(3,5, requires_grad=True)
print(z)
y_hat = F.softmax(z, dim=1) #한 행으로 softmax 해줌
print(y_hat)
print(y_hat.sum(dim=1)) #각 행 /각 행을 다 더한 것  

tensor([[0.1655, 0.2826, 0.8281, 0.1035, 0.6487],
        [0.0904, 0.1194, 0.5691, 0.3044, 0.7190],
        [0.2636, 0.3645, 0.7438, 0.3079, 0.5765]], requires_grad=True)
tensor([[0.1509, 0.1697, 0.2928, 0.1419, 0.2447],
        [0.1480, 0.1523, 0.2389, 0.1833, 0.2775],
        [0.1630, 0.1803, 0.2635, 0.1704, 0.2229]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [53]:
y = torch.randint(5, (3,)).long()
print(y) #0부터 4까지의 값을 랜덤하게 3개를 발생시킴
print(y_hat) #첫 번째 값은 1행을 인코딩하고 나머지는 0으로, 두 번째 값은 2행을 인코딩하고 나머지는 0으로...
y_one_hot = torch.zeros_like(y_hat)
print(y_one_hot)
print(y.unsqueeze(1)) #크기가 1인 2차원을 하나 만듦
y_one_hot.scatter_(1, y.unsqueeze(1), 1)
print(y_one_hot)

tensor([3, 3, 1])
tensor([[0.1509, 0.1697, 0.2928, 0.1419, 0.2447],
        [0.1480, 0.1523, 0.2389, 0.1833, 0.2775],
        [0.1630, 0.1803, 0.2635, 0.1704, 0.2229]], grad_fn=<SoftmaxBackward0>)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[3],
        [3],
        [1]])
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.]])


In [55]:
import sklearn.datasets as datasets
iris =datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [56]:
x_train = torch.FloatTensor(iris.data)
y_train = torch.LongTensor(iris.target)
print (x_train.size())
print (y_train.size())


torch.Size([150, 4])
torch.Size([150])
