In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [8]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]]) #입력값
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]]) #정답

In [9]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)

In [10]:
model = LinearRegressionModel()
print(model)
optimizer = optim.SGD(model.parameters(), lr=0.01)  #SGD 확률적 그라디언트 디센트

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [11]:
epochs = 2001  #epoch 전체 데이터를 한 번 돌리는 것

for epoch in range(epochs):
    y = model(x_data) #이때 forward가 호출됨
    cost = F.mse_loss(y, t_data) #전체에 대한 계산을 한 번에 함
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0: #0번, 100번 ,200번에 한 번씩 찍는 것
        print(epoch, cost.item(), list(model.parameters()))
        


0 39.16685104370117 [Parameter containing:
tensor([[0.9284]], requires_grad=True), Parameter containing:
tensor([-0.3235], requires_grad=True)]
100 0.08463062345981598 [Parameter containing:
tensor([[2.1882]], requires_grad=True), Parameter containing:
tensor([0.3204], requires_grad=True)]
200 0.04298952594399452 [Parameter containing:
tensor([[2.1342]], requires_grad=True), Parameter containing:
tensor([0.5157], requires_grad=True)]
300 0.021837208420038223 [Parameter containing:
tensor([[2.0956]], requires_grad=True), Parameter containing:
tensor([0.6548], requires_grad=True)]
400 0.01109258271753788 [Parameter containing:
tensor([[2.0681]], requires_grad=True), Parameter containing:
tensor([0.7540], requires_grad=True)]
500 0.00563468411564827 [Parameter containing:
tensor([[2.0486]], requires_grad=True), Parameter containing:
tensor([0.8246], requires_grad=True)]
600 0.0028622171375900507 [Parameter containing:
tensor([[2.0346]], requires_grad=True), Parameter containing:
tensor([0

In [12]:
predict = (model(torch.FloatTensor([[7], [8]]))) #데이터는 2차원 형태로 들어가야 함 #이때 forward가 호출됨
print(predict) 

tensor([[15.0010],
        [17.0013]], grad_fn=<AddmmBackward0>)


In [19]:
import pandas as pd
df=pd.read_csv('../data/data-01-test-score.csv', header=None) #header=None을 해야 첫 번째 데이터가 헤더로 안 들어감
x_data = df.values[:, :-1] #values를 넣으면 배열 형태로 출력됨 , 0부터 마지막열 앞까지
t_data = df.values[:, -1]
print(x_data.shape, t_data.shape)
t_data=t_data.reshape(-1, 1)
print(x_data.shape, t_data.shape)
print(type(x_data), type(t_data)) #훈련시키려면 텐서플로우로 만들어 주어야 함
x_data1 = torch.from_numpy(x_data).float()
t_data1 = torch.from_numpy(t_data).float()
print(type(x_data1), type(t_data1)) #훈련데이터를 출력함

indim = x_data1.size(1)
print(indim)

(25, 3) (25,)
(25, 3) (25, 1)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>
3


In [20]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear= nn.Linear(indim,1) #size1의 크기를 변수로 받아서, 그 변수를 숫자 대신에 입력해도 됨
    def forward(self, x):
        return self.linear(x)

In [21]:
model = MultiLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr = 1e-6)

In [24]:
epochs = 200001
for epoch in range(epochs):
    y = model(x_data1)
    cost = F.mse_loss(y, t_data1)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(epoch, cost.item(), list(model.parameters()))

0 6.393212795257568 [Parameter containing:
tensor([[0.4788, 0.5026, 1.0375]], requires_grad=True), Parameter containing:
tensor([-0.2223], requires_grad=True)]
100 6.391359806060791 [Parameter containing:
tensor([[0.4785, 0.5026, 1.0378]], requires_grad=True), Parameter containing:
tensor([-0.2223], requires_grad=True)]
200 6.389508247375488 [Parameter containing:
tensor([[0.4782, 0.5026, 1.0381]], requires_grad=True), Parameter containing:
tensor([-0.2224], requires_grad=True)]
300 6.3876633644104 [Parameter containing:
tensor([[0.4779, 0.5026, 1.0384]], requires_grad=True), Parameter containing:
tensor([-0.2224], requires_grad=True)]
400 6.385822772979736 [Parameter containing:
tensor([[0.4776, 0.5026, 1.0387]], requires_grad=True), Parameter containing:
tensor([-0.2224], requires_grad=True)]
500 6.384018421173096 [Parameter containing:
tensor([[0.4772, 0.5026, 1.0390]], requires_grad=True), Parameter containing:
tensor([-0.2224], requires_grad=True)]
600 6.382180213928223 [Parameter

In [25]:
x=torch.FloatTensor([[75, 85, 90],[90, 85,75]])
model(x)

tensor([[173.2171],
        [161.6535]], grad_fn=<AddmmBackward0>)