In [1]:
def my_fun1(x):
    return x**2


In [8]:
def my_fun2(x):
    return 2*x**2+3*x+1

In [7]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    
    return (f(x+delta_x) -f(x-delta_x)) / (2*delta_x)

In [9]:
result2 = numerical_derivative(my_fun2, 2)
print(result2)

11.00000000000989


2x**2 + 3x+1

In [5]:
result = numerical_derivative (my_fun1, 3) #x에 3을 넣음음
print(result)

6.000000000012662


In [14]:
import numpy as np
def numerical_derivative2(f, x):  #수치미분 debug version
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print('x' , x)
    print('grad' , grad)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
#flags :c_index(1차원 array일 때), multi_index(2차원 이상일 때)
#op_flags : 읽기 /쓰기 옵션설정, default:readonly

    while not it.finished:
        idx = it.multi_index
    
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
    
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
    
        print('grad[idx]:' , grad[idx])

        print('grad:' , grad)
    
        x[idx] = tmp_val
        it.iternext()
    

    return grad

In [19]:
def func3(input):
    x=input[0]
    y=input[1]
    return (2*x + 3*x*y +np.power(y,3))

In [20]:
numerical_derivative2(func3, np.array([1.0, 2.0]))

x [1. 2.]
grad [0. 0.]
grad[idx]: 7.999999999990237
grad: [8. 0.]
grad[idx]: 15.000000010019221
grad: [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [18]:
arr1 = np.array([[1.0, 2.0], [3.0, 4.0]])
arr1

array([[1., 2.],
       [3., 4.]])

In [22]:
def func4(input):
    w = input[0][0]
    x = input[0][1]
    y = input[1][0]
    z = input[1][1]
    
    return (w*x + w*y*z +3*w +z*np.power(y,2))

In [23]:
numerical_derivative2(func4, arr1)

x [[1. 2.]
 [3. 4.]]
grad [[0. 0.]
 [0. 0.]]
grad[idx]: 16.999999999995907
grad: [[17.  0.]
 [ 0.  0.]]
grad[idx]: 1.0000000000331966
grad: [[17.  1.]
 [ 0.  0.]]
grad[idx]: 28.000000000041325
grad: [[17.  1.]
 [28.  0.]]
grad[idx]: 12.00000000000756
grad: [[17.  1.]
 [28. 12.]]


array([[17.,  1.],
       [28., 12.]])