In [53]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [54]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1,2],[2,3],[3,4],[4,5],[5,6]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [55]:
model = nn.Linear(2, 1) #input_dim=1, output_dim=1, y=Wx+b #입력이 n개면 가중치도 n개를 만들어야 함함
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True), Parameter containing:
tensor([-0.1371], requires_grad=True)]


In [56]:
optimizer = optim.SGD(model.parameters(), lr=0.01)
epochs = 20001

In [59]:
for epoch in range(epochs):
    h = model(x_data)
    cost = F.mse_loss(h, t_data)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print('epoch:', epoch, 'cost:', cost.item())
    

epoch: 0 cost: 3.0127011996228248e-12
epoch: 100 cost: 3.0127011996228248e-12
epoch: 200 cost: 3.0127011996228248e-12
epoch: 300 cost: 3.0127011996228248e-12
epoch: 400 cost: 3.0127011996228248e-12
epoch: 500 cost: 3.0127011996228248e-12
epoch: 600 cost: 3.0127011996228248e-12
epoch: 700 cost: 3.0127011996228248e-12
epoch: 800 cost: 3.0127011996228248e-12
epoch: 900 cost: 3.0127011996228248e-12
epoch: 1000 cost: 3.0127011996228248e-12
epoch: 1100 cost: 3.0127011996228248e-12
epoch: 1200 cost: 3.0127011996228248e-12
epoch: 1300 cost: 3.0127011996228248e-12
epoch: 1400 cost: 3.0127011996228248e-12
epoch: 1500 cost: 3.0127011996228248e-12
epoch: 1600 cost: 3.0127011996228248e-12
epoch: 1700 cost: 3.0127011996228248e-12
epoch: 1800 cost: 3.0127011996228248e-12
epoch: 1900 cost: 3.0127011996228248e-12
epoch: 2000 cost: 3.0127011996228248e-12
epoch: 2100 cost: 3.0127011996228248e-12
epoch: 2200 cost: 3.0127011996228248e-12
epoch: 2300 cost: 3.0127011996228248e-12
epoch: 2400 cost: 3.01270119

In [61]:
print(model(torch.FloatTensor([[7,8], [8,9], [9,10]])))
print(list(model.parameters()))

tensor([[15.0000],
        [17.0000],
        [19.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.1798, 0.8202]], requires_grad=True), Parameter containing:
tensor([0.1798], requires_grad=True)]
