In [114]:
import numpy as np



In [115]:
x_data1 = np.array([1, 2, 3, 4,5]).reshape(5,1) #열 하나로로 만듦
t_data1=np.array([3,5,7,9,11]).reshape(5,1) #정답 w=2 b=1
print(x_data1)
print(t_data1)



[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [116]:
x_data = np.array([[1,2],[ 2, 3],[3,4],[ 4,5],[5,6]]).reshape(5,2) #열 하나로로 만듦
t_data=np.array([3,5,7,9,11]).reshape(5,1) #정답 w=2 b=1

In [117]:
w = np.random.rand(2, 1)
b=np.random.rand(1)
print(w)
print(b)

[[0.30378478]
 [0.90602325]]
[0.86081479]


In [118]:
#가중치 만들기
w=np.random.rand(1, 1) #실수를 만듦, 1행1열 - x값에 따라 2,1이 됨 x_data1의 열의 개수에 맞추면 됨됨
b= np.random.rand(1)
print(w)
print(b)

[[0.10700989]]
[0.73911653]


In [119]:
#손실함수 만듦
def loss_func1(x, t):
    y=np.dot(x, w)+b
    
    return(np.sum((t-y)**2))/(len(x)) #원래 정답 t와 가상 식에 의해 만들어진 값 y를 빼서 제곱을 한 후 모두 더한 것/x의 길이 => MSE



In [120]:
def numerical_derivative(f, x):  #수치미분 debug version
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
#flags :c_index(1차원 array일 때), multi_index(2차원 이상일 때)
#op_flags : 읽기 /쓰기 옵션설정, default:readonly

    while not it.finished:
        idx = it.multi_index
    
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
    
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
    
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [121]:
def predict(x): #새로운 값으로 예측하려 함
    y=np.dot(x, w)+b
    return y


In [123]:
cost_list=[]
#learning_rate=1e-4 #알파 값
learning_rate=1e-7 #알파 값

f=lambda x:loss_func1(x_data1, t_data1)

print('Initial error value :', loss_func1(x_data1, t_data1), 'Initial w=',w,'Initial b=',b )
#print('Initial error value :', loss_func1(x_data, t_data2) , 'Initial w2=',w2,'Initial b2=',b2 )

for step in range(20000):
    #최솟값이 아니기 때문에 w 변경함
    w-=learning_rate*numerical_derivative(f, w)
    b-=learning_rate*numerical_derivative(f, b)
    
    if step % 100 == 0:
        print('step:', step, 'error value:', loss_func1(x_data1,t_data1), 'w:', w, 'b:',b)

Initial error value : 42.44436539133851 Initial w= [[0.10710989]] Initial b= [0.73911653]
step: 0 error value: 42.44416457952754 w: [[0.10711421]] b: [0.73911772]
step: 100 error value: 42.42408819676299 w: [[0.10754624]] b: [0.7392365]
step: 200 error value: 42.40402131263487 w: [[0.10797818]] b: [0.73935525]
step: 300 error value: 42.38396392264908 w: [[0.10841001]] b: [0.73947397]
step: 400 error value: 42.36391602231373 w: [[0.10884174]] b: [0.73959266]
step: 500 error value: 42.343877607139 w: [[0.10927337]] b: [0.73971132]
step: 600 error value: 42.32384867263721 w: [[0.1097049]] b: [0.73982996]
step: 700 error value: 42.30382921432281 w: [[0.11013632]] b: [0.73994856]
step: 800 error value: 42.283819227712364 w: [[0.11056765]] b: [0.74006714]
step: 900 error value: 42.263818708324536 w: [[0.11099887]] b: [0.74018569]
step: 1000 error value: 42.24382765168015 w: [[0.11142999]] b: [0.74030421]
step: 1100 error value: 42.22384605330211 w: [[0.111861]] b: [0.74042271]
step: 1200 err

In [104]:
predict(np.array([[6,7]]))
predict(np.array([[7,8]]))

array([[10.90121402]])