In [69]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim #손실함수 최적화 시 사용함


In [70]:
torch.manual_seed(1)
x_train = torch.FloatTensor([[1], [2], [3], [4], [5]]) #2차원 TENSOR
y_train = torch.FloatTensor([[2], [4], [6], [8], [10]]) #2차원 TENSOR

print(x_train)
print(y_train)
print(x_train.size())
print(y_train.size())

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.]])
torch.Size([5, 1])
torch.Size([5, 1])


In [71]:
W = torch.zeros(1, requires_grad=True)
print(W)
b = torch.zeros(1, requires_grad=True) #requires_grad=True : 학습을 통해 나중에 변경을 요구하는 함수수
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [72]:
h = x_train*W+b
print(h)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [73]:
cost = torch.mean((h-y_train)**2)
print(cost)

tensor(44., grad_fn=<MeanBackward0>)


In [74]:
#어떤 식으로 내려오는지를 확인함 
#'SGD'는경사하강법의종류,  lr은학습률(learning rate)를의미
# 학습대상인 W와 b가 SGD의 입력됨.
optimizer = optim.SGD([W, b], lr=0.001)

In [75]:
optimizer.zero_grad()

In [76]:
cost.backward()

In [77]:
optimizer.step()

In [78]:
epochs = 20000
for epoch in range(epochs):
    h=x_train*W+b
    
    cost = torch.mean((h-y_train)**2) #cost가 최적화 되도록 개선해야 함
    optimizer.zero_grad() #초기화 시킴
    cost.backward() # 비용함수를 미분하여 gradient 계산
    optimizer.step()
    
    if epoch % 100 == 0: #100번마다 한 번씩 출력
        print('Epoch {:4d}/{} W:{:.3f} b:{:.3f} cost:{:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        )) #{}안에 값이 들어감
        
    

Epoch    0/20000 W:0.087 b:0.024 cost:41.944607
Epoch  100/20000 W:1.701 b:0.452 cost:0.393517
Epoch  200/20000 W:1.852 b:0.476 cost:0.044956
Epoch  300/20000 W:1.870 b:0.464 cost:0.039331
Epoch  400/20000 W:1.875 b:0.449 cost:0.036737
Epoch  500/20000 W:1.880 b:0.434 cost:0.034334
Epoch  600/20000 W:1.884 b:0.420 cost:0.032089
Epoch  700/20000 W:1.888 b:0.406 cost:0.029990
Epoch  800/20000 W:1.891 b:0.392 cost:0.028029
Epoch  900/20000 W:1.895 b:0.379 cost:0.026196
Epoch 1000/20000 W:1.898 b:0.367 cost:0.024483
Epoch 1100/20000 W:1.902 b:0.354 cost:0.022882
Epoch 1200/20000 W:1.905 b:0.343 cost:0.021386
Epoch 1300/20000 W:1.908 b:0.331 cost:0.019987
Epoch 1400/20000 W:1.911 b:0.320 cost:0.018680
Epoch 1500/20000 W:1.914 b:0.310 cost:0.017459
Epoch 1600/20000 W:1.917 b:0.299 cost:0.016317
Epoch 1700/20000 W:1.920 b:0.289 cost:0.015250
Epoch 1800/20000 W:1.923 b:0.280 cost:0.014253
Epoch 1900/20000 W:1.925 b:0.270 cost:0.013321
Epoch 2000/20000 W:1.928 b:0.261 cost:0.012450
Epoch 2100/2

In [79]:
h = torch.FloatTensor([[7], [8], [9]])*W+b
print(h)

tensor([[13.9994],
        [15.9993],
        [17.9991]], grad_fn=<AddBackward0>)


In [80]:
import torch
w = torch.tensor(2.0, requires_grad=True)
print(w)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    z =  2*W
    z.backward()
    print('수식을 w로 미분한 값:{}'.format(w.grad))

tensor(2., requires_grad=True)
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None


In [81]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [82]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [83]:
torch.manual_seed(3)
print('랜덤 시드가 5일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.0043])
tensor([0.1056])


In [84]:
import numpy as np
x_data1 = np.array([[1,2],[2,3],[3,4],[4,5]])
t_data1 = np.array([3, 5, 7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [85]:
x_data = torch.from_numpy(x_data1).float()
t_data = torch.from_numpy(x_data1).float()
print(x_data)
print(t_data)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])
tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])


In [86]:
W = torch.zeros((2,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

In [87]:
optimizer = optim.SGD([w, b], lr=1e-6)
epochs = 20001
for epoch in range(epochs):
    y=x_data.matmul(W) +b
    cost = torch.mean((t_data-y)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('epoch:' , epoch, 'y:', y, cost.item(), 'w:', w, 'b: ', b)

epoch: 0 y: tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>) 10.5 w: tensor(2., requires_grad=True) b:  tensor([6.0000e-06], requires_grad=True)
epoch: 100 y: tensor([[0.0006],
        [0.0006],
        [0.0006],
        [0.0006]], grad_fn=<AddBackward0>) 10.496400833129883 w: tensor(2., requires_grad=True) b:  tensor([0.0006], requires_grad=True)
epoch: 200 y: tensor([[0.0012],
        [0.0012],
        [0.0012],
        [0.0012]], grad_fn=<AddBackward0>) 10.492803573608398 w: tensor(2., requires_grad=True) b:  tensor([0.0012], requires_grad=True)
epoch: 300 y: tensor([[0.0018],
        [0.0018],
        [0.0018],
        [0.0018]], grad_fn=<AddBackward0>) 10.489206314086914 w: tensor(2., requires_grad=True) b:  tensor([0.0018], requires_grad=True)
epoch: 400 y: tensor([[0.0024],
        [0.0024],
        [0.0024],
        [0.0024]], grad_fn=<AddBackward0>) 10.485610961914062 w: tensor(2., requires_grad=True) b:  tensor([0.0024], requires_grad=True)
epo

In [88]:
def predict(x):
    h = x.matmul(W) +b
    return h

In [89]:
predict(torch.FloatTensor([[10, 11]]))

tensor([[0.1176]], grad_fn=<AddBackward0>)

In [90]:
h = torch.FloatTensor([[11, 12]]).matmul(W) + b
print(h)

tensor([[0.1176]], grad_fn=<AddBackward0>)


In [91]:
import pandas as pd
df = pd.read_csv('../data/data-01-test-score.csv', header=None)
df

0   1    2    3
0   73  80   75  152
1   93  88   93  185
2   89  91   90  180
3   96  98  100  196
4   73  66   70  142
5   53  46   55  101
6   69  74   77  149
7   47  56   60  115
8   87  79   90  175
9   79  70   88  164
10  69  70   73  141
11  70  65   74  141
12  93  95   91  184
13  79  80   73  152
14  70  73   78  148
15  93  89   96  192
16  78  75   68  147
17  81  90   93  183
18  88  92   86  177
19  78  83   77  159
20  82  86   90  177
21  86  82   89  175
22  78  83   85  175
23  76  83   71  149
24  96  93   95  192

In [92]:
data = df.values
x_data = data[:, :3].reshape(-1, 3) #모든 행의 인덱스 2까지만  // 행은 몇 개인지 모르고, 열은 3개개

y_data = data[:, -1].reshape(-1, 1) #마지막 열만 가져옴

print(x_data)
print(y_data)


[[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[152]
 [185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]


In [93]:
x_train = torch.from_numpy(x_data).float() #토치의 텐서 데이터로 만듦. 
y_train = torch.from_numpy(y_data).float()
print(x_train)
print(y_train) 

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.],
        [101.],
        [149.],
        [115.],
        [175.],
        [164.],
        [141.],
        [141.],
        [184.],
        [152.],
        [148.],
        [192.],
        [147.],
        [183.],
        [17

In [94]:
W = torch.zeros((3, 1), requires_grad=True) #토치 데이터의 열이 3개이므로 3행으로 만들어야 함 
b = torch.zeros(1, requires_grad=True)
print(W)
print(b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [95]:
cost_list = []
optimizer = optim.SGD([W, b], lr = 1e-6)

epochs=30001

In [96]:
for epoch in range(epochs):
    y = x_train.matmul(W) +b
    cost = torch.mean((y-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    cost_list.append([epoch, cost]) #각 epoch마다 cost를 넣어 줌줌
    
    if epoch %100 == 0:
        print('epoch:', epoch, 'cost: ', cost, 'W', W, 'b:', b)

epoch: 0 cost:  tensor(26811.9609, grad_fn=<MeanBackward0>) W tensor([[0.0262],
        [0.0263],
        [0.0269]], requires_grad=True) b: tensor([0.0003], requires_grad=True)
epoch: 100 cost:  tensor(20.7345, grad_fn=<MeanBackward0>) W tensor([[0.6548],
        [0.6583],
        [0.6764]], requires_grad=True) b: tensor([0.0081], requires_grad=True)
epoch: 200 cost:  tensor(11.6739, grad_fn=<MeanBackward0>) W tensor([[0.6656],
        [0.6690],
        [0.6899]], requires_grad=True) b: tensor([0.0083], requires_grad=True)
epoch: 300 cost:  tensor(11.6277, grad_fn=<MeanBackward0>) W tensor([[0.6650],
        [0.6683],
        [0.6918]], requires_grad=True) b: tensor([0.0083], requires_grad=True)
epoch: 400 cost:  tensor(11.5849, grad_fn=<MeanBackward0>) W tensor([[0.6642],
        [0.6674],
        [0.6935]], requires_grad=True) b: tensor([0.0083], requires_grad=True)
epoch: 500 cost:  tensor(11.5425, grad_fn=<MeanBackward0>) W tensor([[0.6634],
        [0.6665],
        [0.6952]], req

In [98]:
def predict(x) :
    return x.matmul(W) +b

In [99]:
new_data = torch.FloatTensor([[65, 68, 70], [100, 95, 90], [90, 95,100]])
predict(new_data)

tensor([[137.6625],
        [189.2492],
        [194.0849]], grad_fn=<AddBackward0>)