In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim #손실함수 최적화 시 사용함


In [16]:
torch.manual_seed(1)
x_train = torch.FloatTensor([[1], [2], [3], [4], [5]]) #2차원 TENSOR
y_train = torch.FloatTensor([[2], [4], [6], [8], [10]]) #2차원 TENSOR

print(x_train)
print(y_train)
print(x_train.size())
print(y_train.size())

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.]])
torch.Size([5, 1])
torch.Size([5, 1])


In [17]:
W = torch.zeros(1, requires_grad=True)
print(W)
b = torch.zeros(1, requires_grad=True) #requires_grad=True : 학습을 통해 나중에 변경을 요구하는 함수수
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [18]:
h = x_train*W+b
print(h)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [19]:
cost = torch.mean((h-y_train)**2)
print(cost)

tensor(44., grad_fn=<MeanBackward0>)


In [20]:
#어떤 식으로 내려오는지를 확인함 
#'SGD'는경사하강법의종류,  lr은학습률(learning rate)를의미
# 학습대상인 W와 b가 SGD의 입력됨.
optimizer = optim.SGD([W, b], lr=0.001)

In [21]:
optimizer.zero_grad()

In [23]:
cost.backward()

In [ ]:
optimizer.step()

In [26]:
epochs = 20000
for epoch in range(epochs):
    h=x_train*W+b
    
    cost = torch.mean((h-y_train)**2) #cost가 최적화 되도록 개선해야 함
    optimizer.zero_grad() #초기화 시킴
    cost.backward() # 비용함수를 미분하여 gradient 계산
    optimizer.step()
    
    if epoch % 100 == 0: #100번마다 한 번씩 출력
        print('Epoch {:4d}/{} W:{:.3f} b:{:.3f} cost:{:.6f}'.format(
            epoch, epochs, W.item(), b.item(), cost.item()
        )) #{}안에 값이 들어감
        
    

Epoch    0/20000 W:2.000 b:0.001 cost:0.000000
Epoch  100/20000 W:2.000 b:0.001 cost:0.000000
Epoch  200/20000 W:2.000 b:0.001 cost:0.000000
Epoch  300/20000 W:2.000 b:0.001 cost:0.000000
Epoch  400/20000 W:2.000 b:0.001 cost:0.000000
Epoch  500/20000 W:2.000 b:0.001 cost:0.000000
Epoch  600/20000 W:2.000 b:0.000 cost:0.000000
Epoch  700/20000 W:2.000 b:0.000 cost:0.000000
Epoch  800/20000 W:2.000 b:0.000 cost:0.000000
Epoch  900/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1000/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1100/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1200/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1300/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1400/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1500/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1600/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1700/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1800/20000 W:2.000 b:0.000 cost:0.000000
Epoch 1900/20000 W:2.000 b:0.000 cost:0.000000
Epoch 2000/20000 W:2.000 b:0.000 cost:0.000000
Epoch 2100/20

In [29]:
h = torch.FloatTensor([[7], [8], [9]])*W+b
print(h)

tensor([[13.9999],
        [15.9999],
        [17.9999]], grad_fn=<AddBackward0>)


In [27]:
import torch
w = torch.tensor(2.0, requires_grad=True)
print(w)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    z =  2*W
    z.backward()
    print('수식을 w로 미분한 값:{}'.format(w.grad))

tensor(2., requires_grad=True)
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None
수식을 w로 미분한 값:None


In [31]:
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [32]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1, 3):
    print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [ ]:
torch.manual_seed(3)
print('랜덤 시드가 5일 때')
for i in range(1, 3):
    print(torch.rand(1))

In [33]:
import numpy as np
x_data1 = np.array([[1,2],[2,3],[3,4],[4,5]])
t_data1 = np.array([3, 5, 7,9,11]).reshape(5,1)
print(x_data1)
print(t_data1)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [36]:
x_data = torch.from_numpy(x_data1).float()
t_data = torch.from_numpy(x_data1).float()
print(x_data)
print(t_data)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])
tensor([[1., 2.],
        [2., 3.],
        [3., 4.],
        [4., 5.]])


In [37]:
W = torch.zeros((2,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

In [43]:
optimizer = optim.SGD([w, b], lr=1e-6)
epochs = 20001
for epoch in range(epochs):
    y=x_data.matmul(W) +b
    cost = torch.mean((t_data-y)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('epoch:' , epoch, 'y:', y, cost.item(), 'w:', w, 'b: ', b)

epoch: 0 y: tensor([[0.1176],
        [0.1176],
        [0.1176],
        [0.1176]], grad_fn=<AddBackward0>) 9.808015823364258 w: tensor(2., requires_grad=True) b:  tensor([0.1176], requires_grad=True)
epoch: 100 y: tensor([[0.1182],
        [0.1182],
        [0.1182],
        [0.1182]], grad_fn=<AddBackward0>) 9.804691314697266 w: tensor(2., requires_grad=True) b:  tensor([0.1182], requires_grad=True)
epoch: 200 y: tensor([[0.1188],
        [0.1188],
        [0.1188],
        [0.1188]], grad_fn=<AddBackward0>) 9.801370620727539 w: tensor(2., requires_grad=True) b:  tensor([0.1188], requires_grad=True)
epoch: 300 y: tensor([[0.1194],
        [0.1194],
        [0.1194],
        [0.1194]], grad_fn=<AddBackward0>) 9.798051834106445 w: tensor(2., requires_grad=True) b:  tensor([0.1194], requires_grad=True)
epoch: 400 y: tensor([[0.1199],
        [0.1199],
        [0.1199],
        [0.1199]], grad_fn=<AddBackward0>) 9.794734954833984 w: tensor(2., requires_grad=True) b:  tensor([0.1199], re

In [47]:
def predict(x):
    h = x.matmul(W) +b
    return h

In [48]:
predict(torch.FloatTensor([[10, 11]]))

tensor([[0.2307]], grad_fn=<AddBackward0>)

In [49]:
h = torch.FloatTensor([[11, 12]]).matmul(W) + b
print(h)

tensor([[0.2307]], grad_fn=<AddBackward0>)
